#!/usr/bin/env python
import sys
import optparse
import select
import termios
from src.debugger import *
from src.ui import CursesUI

if __name__ == "__main__":
    parser = optparse.OptionParser(description="DBGP debugger for PHP scripts")
    parser.add_option('--host', action='store', default='127.0.0.1', help='Host (defaults to 127.0.0.1)')
    parser.add_option('--port', action='store', default=9000, help='Port (defaults to 9000)')
    options, args = parser.parse_args()
    if len(args) < 1:
        parser.error("You need to specify a path")

    debugger = Debugger(args[0], CursesUI(), options.port, options.host)

    ## New even loop
    inputs = [0, debugger.server_socket]

    while debugger.alive:
        inp_ready, out_ready, xtr_ready = select.select(inputs, [], [])

        for thing in inp_ready:
            if thing == 0: # STDIN
                try:
                    debugger.ui.tick()
                finally:
                    debugger.ui.stop()

            elif thing == debugger.server_socket:
                # Accept new clients
                sock = debugger.new_client()

                if sock:
                    inputs.append(sock)

            else:
                # It must be clients
                if not debugger.handle_client(thing):
                    inputs.remove(thing)
    #try:
    #    debugger.start()
    #    debugger.ui.start()
    #except KeyboardInterrupt:
    #    pass
    #finally:
    #    debugger.stop()
